-- El Impostor - Database Schema
-- Run this in Supabase SQL Editor

-- Categories table
CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  name_es TEXT NOT NULL,
  name_en TEXT,
  name_ca TEXT,
  name_gl TEXT,
  name_eu TEXT
);

-- Words table
CREATE TABLE words (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  word TEXT NOT NULL,
  category_id TEXT REFERENCES categories(id) ON DELETE CASCADE,
  lang TEXT DEFAULT 'es',
  approved BOOLEAN DEFAULT false,
  suggested_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for frequent queries
CREATE INDEX idx_words_category_lang ON words(category_id, lang) WHERE approved = true;
CREATE INDEX idx_words_pending ON words(approved) WHERE approved = false;

-- Enable Row Level Security
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE words ENABLE ROW LEVEL SECURITY;

-- Policies: Everyone can read approved words and categories
CREATE POLICY "Anyone can read categories" ON categories
  FOR SELECT USING (true);

CREATE POLICY "Anyone can read approved words" ON words
  FOR SELECT USING (approved = true);

-- Authenticated users can suggest words
CREATE POLICY "Authenticated users can suggest words" ON words
  FOR INSERT TO authenticated
  WITH CHECK (approved = false AND suggested_by = auth.uid());

-- Seed initial categories
INSERT INTO categories (id, name_es, name_en) VALUES
  ('animals', 'Animales', 'Animals'),
  ('food', 'Comida', 'Food'),
  ('places', 'Lugares', 'Places'),
  ('objects', 'Objetos', 'Objects'),
  ('professions', 'Profesiones', 'Professions'),
  ('sports', 'Deportes', 'Sports');

-- Seed initial words (approved) - ~50 per category
INSERT INTO words (word, category_id, lang, approved) VALUES
  -- Animals (50)
  ('Perro', 'animals', 'es', true),
  ('Gato', 'animals', 'es', true),
  ('Elefante', 'animals', 'es', true),
  ('León', 'animals', 'es', true),
  ('Delfín', 'animals', 'es', true),
  ('Águila', 'animals', 'es', true),
  ('Serpiente', 'animals', 'es', true),
  ('Caballo', 'animals', 'es', true),
  ('Tigre', 'animals', 'es', true),
  ('Oso', 'animals', 'es', true),
  ('Jirafa', 'animals', 'es', true),
  ('Cebra', 'animals', 'es', true),
  ('Mono', 'animals', 'es', true),
  ('Pingüino', 'animals', 'es', true),
  ('Cocodrilo', 'animals', 'es', true),
  ('Tiburón', 'animals', 'es', true),
  ('Ballena', 'animals', 'es', true),
  ('Tortuga', 'animals', 'es', true),
  ('Conejo', 'animals', 'es', true),
  ('Ratón', 'animals', 'es', true),
  ('Lobo', 'animals', 'es', true),
  ('Zorro', 'animals', 'es', true),
  ('Cerdo', 'animals', 'es', true),
  ('Vaca', 'animals', 'es', true),
  ('Oveja', 'animals', 'es', true),
  ('Gallina', 'animals', 'es', true),
  ('Pato', 'animals', 'es', true),
  ('Búho', 'animals', 'es', true),
  ('Loro', 'animals', 'es', true),
  ('Cangrejo', 'animals', 'es', true),
  ('Pulpo', 'animals', 'es', true),
  ('Medusa', 'animals', 'es', true),
  ('Araña', 'animals', 'es', true),
  ('Mariposa', 'animals', 'es', true),
  ('Abeja', 'animals', 'es', true),
  ('Hormiga', 'animals', 'es', true),
  ('Caracol', 'animals', 'es', true),
  ('Rana', 'animals', 'es', true),
  ('Hipopótamo', 'animals', 'es', true),
  ('Rinoceronte', 'animals', 'es', true),
  ('Camello', 'animals', 'es', true),
  ('Canguro', 'animals', 'es', true),
  ('Koala', 'animals', 'es', true),
  ('Panda', 'animals', 'es', true),
  ('Gorila', 'animals', 'es', true),
  ('Foca', 'animals', 'es', true),
  ('Murciélago', 'animals', 'es', true),
  ('Ciervo', 'animals', 'es', true),
  ('Ardilla', 'animals', 'es', true),
  ('Erizo', 'animals', 'es', true),

  -- Food (50)
  ('Pizza', 'food', 'es', true),
  ('Hamburguesa', 'food', 'es', true),
  ('Sushi', 'food', 'es', true),
  ('Paella', 'food', 'es', true),
  ('Tortilla', 'food', 'es', true),
  ('Helado', 'food', 'es', true),
  ('Chocolate', 'food', 'es', true),
  ('Pasta', 'food', 'es', true),
  ('Ensalada', 'food', 'es', true),
  ('Tacos', 'food', 'es', true),
  ('Arroz', 'food', 'es', true),
  ('Pan', 'food', 'es', true),
  ('Queso', 'food', 'es', true),
  ('Jamón', 'food', 'es', true),
  ('Pollo', 'food', 'es', true),
  ('Pescado', 'food', 'es', true),
  ('Huevo', 'food', 'es', true),
  ('Patatas fritas', 'food', 'es', true),
  ('Sopa', 'food', 'es', true),
  ('Gazpacho', 'food', 'es', true),
  ('Croquetas', 'food', 'es', true),
  ('Churros', 'food', 'es', true),
  ('Tarta', 'food', 'es', true),
  ('Galletas', 'food', 'es', true),
  ('Croissant', 'food', 'es', true),
  ('Bocadillo', 'food', 'es', true),
  ('Burrito', 'food', 'es', true),
  ('Nachos', 'food', 'es', true),
  ('Kebab', 'food', 'es', true),
  ('Hot dog', 'food', 'es', true),
  ('Lasaña', 'food', 'es', true),
  ('Risotto', 'food', 'es', true),
  ('Ramen', 'food', 'es', true),
  ('Curry', 'food', 'es', true),
  ('Falafel', 'food', 'es', true),
  ('Hummus', 'food', 'es', true),
  ('Guacamole', 'food', 'es', true),
  ('Empanada', 'food', 'es', true),
  ('Ceviche', 'food', 'es', true),
  ('Brownie', 'food', 'es', true),
  ('Donut', 'food', 'es', true),
  ('Crepe', 'food', 'es', true),
  ('Waffle', 'food', 'es', true),
  ('Palomitas', 'food', 'es', true),
  ('Caramelo', 'food', 'es', true),
  ('Chicle', 'food', 'es', true),
  ('Manzana', 'food', 'es', true),
  ('Plátano', 'food', 'es', true),
  ('Sandía', 'food', 'es', true),
  ('Fresa', 'food', 'es', true),

  -- Places (50)
  ('Playa', 'places', 'es', true),
  ('Montaña', 'places', 'es', true),
  ('Hospital', 'places', 'es', true),
  ('Aeropuerto', 'places', 'es', true),
  ('Biblioteca', 'places', 'es', true),
  ('Restaurante', 'places', 'es', true),
  ('Cine', 'places', 'es', true),
  ('Parque', 'places', 'es', true),
  ('Museo', 'places', 'es', true),
  ('Estadio', 'places', 'es', true),
  ('Supermercado', 'places', 'es', true),
  ('Farmacia', 'places', 'es', true),
  ('Banco', 'places', 'es', true),
  ('Iglesia', 'places', 'es', true),
  ('Universidad', 'places', 'es', true),
  ('Colegio', 'places', 'es', true),
  ('Gimnasio', 'places', 'es', true),
  ('Piscina', 'places', 'es', true),
  ('Zoo', 'places', 'es', true),
  ('Acuario', 'places', 'es', true),
  ('Teatro', 'places', 'es', true),
  ('Discoteca', 'places', 'es', true),
  ('Bar', 'places', 'es', true),
  ('Cafetería', 'places', 'es', true),
  ('Panadería', 'places', 'es', true),
  ('Peluquería', 'places', 'es', true),
  ('Gasolinera', 'places', 'es', true),
  ('Estación de tren', 'places', 'es', true),
  ('Metro', 'places', 'es', true),
  ('Puerto', 'places', 'es', true),
  ('Castillo', 'places', 'es', true),
  ('Palacio', 'places', 'es', true),
  ('Catedral', 'places', 'es', true),
  ('Cementerio', 'places', 'es', true),
  ('Jardín', 'places', 'es', true),
  ('Bosque', 'places', 'es', true),
  ('Desierto', 'places', 'es', true),
  ('Selva', 'places', 'es', true),
  ('Isla', 'places', 'es', true),
  ('Lago', 'places', 'es', true),
  ('Río', 'places', 'es', true),
  ('Cascada', 'places', 'es', true),
  ('Volcán', 'places', 'es', true),
  ('Cueva', 'places', 'es', true),
  ('Faro', 'places', 'es', true),
  ('Puente', 'places', 'es', true),
  ('Torre', 'places', 'es', true),
  ('Rascacielos', 'places', 'es', true),
  ('Fábrica', 'places', 'es', true),
  ('Granja', 'places', 'es', true),

  -- Objects (50)
  ('Teléfono', 'objects', 'es', true),
  ('Ordenador', 'objects', 'es', true),
  ('Televisión', 'objects', 'es', true),
  ('Reloj', 'objects', 'es', true),
  ('Lámpara', 'objects', 'es', true),
  ('Silla', 'objects', 'es', true),
  ('Mesa', 'objects', 'es', true),
  ('Coche', 'objects', 'es', true),
  ('Bicicleta', 'objects', 'es', true),
  ('Libro', 'objects', 'es', true),
  ('Bolígrafo', 'objects', 'es', true),
  ('Lápiz', 'objects', 'es', true),
  ('Tijeras', 'objects', 'es', true),
  ('Gafas', 'objects', 'es', true),
  ('Paraguas', 'objects', 'es', true),
  ('Maleta', 'objects', 'es', true),
  ('Mochila', 'objects', 'es', true),
  ('Cartera', 'objects', 'es', true),
  ('Llaves', 'objects', 'es', true),
  ('Espejo', 'objects', 'es', true),
  ('Cámara', 'objects', 'es', true),
  ('Micrófono', 'objects', 'es', true),
  ('Auriculares', 'objects', 'es', true),
  ('Guitarra', 'objects', 'es', true),
  ('Piano', 'objects', 'es', true),
  ('Batería', 'objects', 'es', true),
  ('Balón', 'objects', 'es', true),
  ('Raqueta', 'objects', 'es', true),
  ('Patines', 'objects', 'es', true),
  ('Monopatín', 'objects', 'es', true),
  ('Sofá', 'objects', 'es', true),
  ('Cama', 'objects', 'es', true),
  ('Armario', 'objects', 'es', true),
  ('Nevera', 'objects', 'es', true),
  ('Microondas', 'objects', 'es', true),
  ('Lavadora', 'objects', 'es', true),
  ('Plancha', 'objects', 'es', true),
  ('Aspiradora', 'objects', 'es', true),
  ('Ventilador', 'objects', 'es', true),
  ('Aire acondicionado', 'objects', 'es', true),
  ('Escalera', 'objects', 'es', true),
  ('Martillo', 'objects', 'es', true),
  ('Destornillador', 'objects', 'es', true),
  ('Vela', 'objects', 'es', true),
  ('Linterna', 'objects', 'es', true),
  ('Brújula', 'objects', 'es', true),
  ('Mapa', 'objects', 'es', true),
  ('Globo terráqueo', 'objects', 'es', true),
  ('Calendario', 'objects', 'es', true),
  ('Despertador', 'objects', 'es', true),

  -- Professions (50)
  ('Médico', 'professions', 'es', true),
  ('Profesor', 'professions', 'es', true),
  ('Bombero', 'professions', 'es', true),
  ('Policía', 'professions', 'es', true),
  ('Chef', 'professions', 'es', true),
  ('Piloto', 'professions', 'es', true),
  ('Arquitecto', 'professions', 'es', true),
  ('Abogado', 'professions', 'es', true),
  ('Veterinario', 'professions', 'es', true),
  ('Astronauta', 'professions', 'es', true),
  ('Ingeniero', 'professions', 'es', true),
  ('Programador', 'professions', 'es', true),
  ('Diseñador', 'professions', 'es', true),
  ('Periodista', 'professions', 'es', true),
  ('Fotógrafo', 'professions', 'es', true),
  ('Actor', 'professions', 'es', true),
  ('Cantante', 'professions', 'es', true),
  ('Músico', 'professions', 'es', true),
  ('Bailarín', 'professions', 'es', true),
  ('Pintor', 'professions', 'es', true),
  ('Escultor', 'professions', 'es', true),
  ('Escritor', 'professions', 'es', true),
  ('Científico', 'professions', 'es', true),
  ('Biólogo', 'professions', 'es', true),
  ('Químico', 'professions', 'es', true),
  ('Físico', 'professions', 'es', true),
  ('Matemático', 'professions', 'es', true),
  ('Economista', 'professions', 'es', true),
  ('Psicólogo', 'professions', 'es', true),
  ('Dentista', 'professions', 'es', true),
  ('Enfermero', 'professions', 'es', true),
  ('Farmacéutico', 'professions', 'es', true),
  ('Electricista', 'professions', 'es', true),
  ('Fontanero', 'professions', 'es', true),
  ('Carpintero', 'professions', 'es', true),
  ('Mecánico', 'professions', 'es', true),
  ('Jardinero', 'professions', 'es', true),
  ('Peluquero', 'professions', 'es', true),
  ('Camarero', 'professions', 'es', true),
  ('Recepcionista', 'professions', 'es', true),
  ('Secretario', 'professions', 'es', true),
  ('Contable', 'professions', 'es', true),
  ('Vendedor', 'professions', 'es', true),
  ('Detective', 'professions', 'es', true),
  ('Juez', 'professions', 'es', true),
  ('Político', 'professions', 'es', true),
  ('Militar', 'professions', 'es', true),
  ('Agricultor', 'professions', 'es', true),
  ('Pescador', 'professions', 'es', true),
  ('Panadero', 'professions', 'es', true),

  -- Sports (50)
  ('Fútbol', 'sports', 'es', true),
  ('Baloncesto', 'sports', 'es', true),
  ('Tenis', 'sports', 'es', true),
  ('Natación', 'sports', 'es', true),
  ('Ciclismo', 'sports', 'es', true),
  ('Golf', 'sports', 'es', true),
  ('Boxeo', 'sports', 'es', true),
  ('Surf', 'sports', 'es', true),
  ('Esquí', 'sports', 'es', true),
  ('Atletismo', 'sports', 'es', true),
  ('Voleibol', 'sports', 'es', true),
  ('Béisbol', 'sports', 'es', true),
  ('Rugby', 'sports', 'es', true),
  ('Hockey', 'sports', 'es', true),
  ('Balonmano', 'sports', 'es', true),
  ('Waterpolo', 'sports', 'es', true),
  ('Gimnasia', 'sports', 'es', true),
  ('Esgrima', 'sports', 'es', true),
  ('Judo', 'sports', 'es', true),
  ('Karate', 'sports', 'es', true),
  ('Taekwondo', 'sports', 'es', true),
  ('Lucha libre', 'sports', 'es', true),
  ('Halterofilia', 'sports', 'es', true),
  ('Remo', 'sports', 'es', true),
  ('Piragüismo', 'sports', 'es', true),
  ('Vela', 'sports', 'es', true),
  ('Windsurf', 'sports', 'es', true),
  ('Buceo', 'sports', 'es', true),
  ('Escalada', 'sports', 'es', true),
  ('Senderismo', 'sports', 'es', true),
  ('Patinaje', 'sports', 'es', true),
  ('Snowboard', 'sports', 'es', true),
  ('Triatlón', 'sports', 'es', true),
  ('Maratón', 'sports', 'es', true),
  ('Salto de altura', 'sports', 'es', true),
  ('Lanzamiento de jabalina', 'sports', 'es', true),
  ('Tiro con arco', 'sports', 'es', true),
  ('Equitación', 'sports', 'es', true),
  ('Polo', 'sports', 'es', true),
  ('Críquet', 'sports', 'es', true),
  ('Bádminton', 'sports', 'es', true),
  ('Ping pong', 'sports', 'es', true),
  ('Billar', 'sports', 'es', true),
  ('Dardos', 'sports', 'es', true),
  ('Bolos', 'sports', 'es', true),
  ('Ajedrez', 'sports', 'es', true),
  ('Parkour', 'sports', 'es', true),
  ('Skateboarding', 'sports', 'es', true),
  ('BMX', 'sports', 'es', true),
  ('Motocross', 'sports', 'es', true);
